# Generated by Django 5.2.4 on 2025-07-05 12:03

from django.db import migrations, models
from django.utils.text import slugify

def populate_slugs(apps, schema_editor):
    Category = apps.get_model('homepage', 'Category')
    for c in Category.objects.all():
        if not c.slug:
            c.slug = slugify(c.name)
            c.save()

class Migration(migrations.Migration):

    dependencies = [
        ('homepage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.RunPython(populate_slugs),
    ]
